### ISSUE TITLE
Mismatch Between OpenAPI Specifications in the Documentation and the Repository

### ISSUE THREAD

**Issue by DKierner** [InterNetX/js-domainrobot-sdk#113]
There seems to be a mismatch between the OpenAPI specification that is supplied in the documentation and the repository.
Look at these links:
* https://raw.githubusercontent.com/InterNetX/internetx-swagger-files/master/src/domainrobot.json
* https://raw.githubusercontent.com/InterNetX/js-domainrobot-sdk/master/src/swagger/domainrobot.json

The latest commit does not update the OpenAPI specification and the updated OpenAPI spec differs from the latest commit. At least, that is what is visible in the error logs shown in https://github.com/InterNetX/js-domainrobot-sdk/issues/112.
As the OpenAPI specifications are generated files, it might be better to remove it from the code repository and add them to `.gitignore`, if saving them to the JavaScript SDK repository was not intended.

**Comment by adelholtz** [comment]
Hi

sorry for the late reply. As mentioned in https://github.com/InterNetX/js-domainrobot-sdk/issues/114 the swagger files used in this SDK should not be used as a reference or to create an API out of them as it can be significantly outdated and is just used for data integrity purposes in this SDK.

Thank you for reporting this issue
