### ISSUE TITLE
fix case-sensitive require in index.js

### ISSUE THREAD

**Issue by mashpie** [InterNetX/js-domainrobot-sdk#2]
Thanks for providing that SDK finally! More a hint than an issue, but please also care for consistent and proper cases in filenames to align with `require`.

given (in `./index.js`):

```js
require("./src/DomainRobot");
```

should read

```js
require("./src/Domainrobot");
```

with file at `src/Domainrobot.js` to proper resolve on all filesystems. 

Currently an import

```js
import { DomainRobot } from 'js-domainrobot-sdk'
```

throws

```bash
ERROR  Failed to compile with 1 errors                                                                                              
This relative module was not found:

* ./src/DomainRobot in ./node_modules/js-domainrobot-sdk/index.js
```

on Webpack compile.

**Comment by adelholtz** [comment]
Hi,

thank you for usind the sdk and making us aware of this problem.
We just released a fix for this problem.
Have a nice day!
